# build angular app using node.js, then deploy to azure static website

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install -g @angular/cli
        npm install
        npm run updata
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: angular-app
        path: app/dist

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: angular-app

    - name: 'Deploy to Azure Static Website'
      id: deploy-to-static-web 
      uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
      with:
        source-path: chaincompare
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
